version: "3.8"

# define the services/containers to be run
services:
  web:
    build: .
    ports:
      - 5173:5173
    env_file:
      - .env
    develop:
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container if there are any changes
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        # it'll watch for changes in the frontend directory and sync the changes with the container real time
        - path: .
          target: /app
          action: sync